### ISSUE TITLE
exit market maker on testnet theta not working

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/burner-wallet#155] opened 2019-06-07 07:46 UTC
details: https://github.com/leapdao/burner-wallet/pull/133#issuecomment-499464267

<img width="428" alt="Screen Shot 2019-06-07 at 9 54 29 AM" src="https://user-images.githubusercontent.com/659301/59089389-457cdd00-890a-11e9-917e-e6d39d35962b.png">

**Comment by troggy** [comment] 2019-06-07 11:54
cannot reproduce. Have just successfully exited both with Metamask (Rinkeby) and without.

Used machine gun to push network till the next period.

However I've found two other issues with EMM: 
https://github.com/leapdao/exit-market-maker/issues/12
https://github.com/leapdao/exit-market-maker/issues/13

**Comment by TimDaub** [comment] 2019-07-01 14:03
I tested this before merging #133 and didn't come across this issue. Hence I'm closing.

**Closed by TimDaub** 2019-07-01 14:03 UTC
Labels: bug
