### ISSUE TITLE
network displayed as unknown if no web3 provider injected

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/burner-wallet#26] opened 2019-04-12 12:36 UTC
<img width="826" alt="Screenshot 2019-04-12 at 13 50 06" src="https://user-images.githubusercontent.com/659301/56037734-56f1a080-5d30-11e9-8fde-27926a9a284e.png">

**Comment by TimDaub** [comment] 2019-04-18 11:47
I noticed that this doesn't happen on `localhost` but on burner.leapdao.org.

**Comment by TimDaub** [comment] 2019-04-18 15:25
I added a fix to dapparatus. No idea if it works, as I couldn't reproduce 🤷‍♂️: https://github.com/leapdao/dapparatus/pull/2/commits/2430a2d4642f46d41fb8c5c294446d909acbdec2

We could just hardcode "LeapTestnet" of course.

**Comment by TimDaub** [comment] 2019-04-18 16:28
Fixed in #37

**Closed by TimDaub** 2019-04-18 16:28 UTC
